library:
  source-dirs: src
tests:
  chapter10-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chapter10
copyright: 2019 Barry Moore
maintainer: moore0557@gmail.com
dependencies:
- transformers
- base >= 4.7 && < 5
name: chapter10
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Barry Moore
github: barrymoo/chapter10
license: BSD3
executables:
  chapter10-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chapter10
description: Please see the README on GitHub at <https://github.com/barrymoo/chapter10#readme>
