library:
  source-dirs: src
tests:
  chapter14-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chapter14
copyright: 2020 Barry Moore
maintainer: moore0557@gmail.com
dependencies:
- random
- base >= 4.7 && < 5
name: chapter14
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Barry Moore
github: barrymoo/chapter14
license: BSD3
executables:
  chapter14-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chapter14
description: Please see the README on GitHub at <https://github.com/barrymoo/chapter14#readme>
