name:                chapter13
version:             0.1.0.0
github:              "barrymoo/chapter13"
license:             BSD3
author:              "Barry Moore"
maintainer:          "moore0557@gmail.com"
copyright:           "2019 Barry Moore"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/barrymoo/chapter13#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- transformers
- random

library:
  source-dirs: src

executables:
  chapter13-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chapter13

tests:
  chapter13-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chapter13
